version: 0.22.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore source\Khala.EventSourcing.sln
build:
  verbosity: minimal
  project: source\Khala.EventSourcing.sln
after_build:
test:
  assemblies: '**\*.tests.dll'
artifacts:
- path: '**\Khala.EventSourcing**.nupkg'