version: 0.9.{build}
configuration: Release
before_build:
- cmd: nuget restore source\Khala.EventSourcing.sln
build:
  verbosity: minimal
  project: source\Khala.EventSourcing.sln
after_build:
- cmd: >-
    nuget pack nuget\Khala.EventSourcing.Core.nuspec

    nuget pack nuget\Khala.EventSourcing.Azure.nuspec

    nuget pack nuget\Khala.EventSourcing.Sql.nuspec
test:
  assemblies: '**\*.tests.dll'
artifacts:
- path: Khala.EventSourcing**.nupkg